# 1.Print 'Hello HCIA'.

In [2]:
print ('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [3]:
a=2
b=3
print(a+b)

5


# 3.Define a list and replicate in three different ways.

In [5]:
#define
old_list=[1,2,3,4,5]
print(old_list[:])
print(old_list)
print()
#Method 1:
new_list = old_list[:]
print(new_list)
print()
#Method 2:
new_list = list(old_list)
print(new_list)
print()
#Method 3:
import copy
new_list1 = copy.copy(old_list)
print(new_list1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


# 4.Define two lists and merge them together.

In [13]:
first_list = [1,2,3,4,5]
second_list = [6,7,8,9,10]
merged_list = first_list + second_list

# 5. Get the last element of the list and print it.

In [8]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print (list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# 6.Define a tuple that contains only one element.

In [11]:
tup = (1)
print (tup)

# 7.Define a three-line long string.

In [33]:
c = '''это очень большая строка
...многострочный
... блок текста'''
print (c)

это очень большая строка
...многострочный
... блок текста


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [20]:
a=[1,2,3,4,5]
for i in a[0:5]:
    print(i)

1
2
3
4
5


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [2]:
def func(x,y):
    return x*y
print (func(6,4))

24


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [12]:
import numpy as np
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [13]:
import numpy as np
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [20]:
a = np.array(range(15))
a
a = a.reshape((3, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [29]:
A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [30]:
B = np.arange(6).reshape(2,3)
B

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
np.matmul(A,B)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])